### ISSUE TITLE
Call to a member function newPage() on null

### ISSUE THREAD

**Issue by binarysilo** [zoonru/puphpeteer#7]
**Describe the bug**
When I try to run the `newPage()` method, I receive an error 

  Call to a member function newPage() on null

**Reproducible example**
```php
        $puppeteer = new Puppeteer;
        $browser = $puppeteer->launch();
        $page = $browser->newPage();
        $page->goto('https://example.com', ['waitUntil' => 'domcontentloaded']);
```

**Comment by xtrime-ru** [comment]
Hi! 
I suggest to check logs for additional errors. Probably there are issues with installation of puppeteer, or npm packages.
