### ISSUE TITLE
Page->querySelector doesn't work

### ISSUE THREAD

**Issue by sylvainlepetit** [zoonru/puphpeteer#8]
**Describe the bug**
      
The variable $page returned by  $browser->newPage(); (see code below) is not a Page \Nesk\Puphpeteer\Resources\Page but a   Nesk\Rialto\Data\BasicResource. So functions like querySelector doesn't work (like all methods from Page)

**Reproducible example**
```php
 $options = [
    'args' => [
        '--no-sandbox',
        '--disable-web-security',
        '--disable-setuid-sandbox',
        '--allow-file-access-from-files',
    ],
    'log_browser_console' => true,
    'log_node_console' => false,
    'debug' => false,
];

$puppeteer = new Puppeteer($options);
$browser = $puppeteer->launch([
    'headless' => 'new',
    'defaultViewport' => ['width' => 1920, 'height' => 1080]
]);
$page = $browser->newPage();
$page->goto($url);
$page->emulateMediaType('screen');
// $page->waitForTimeout(2000);
$page->waitForSelector(self::SELECTOR_CHART_ARE_LOADED);
$tableau = $page->querySelector('.position-relative');
```

Exception returned:   [Nesk\Rialto\Exceptions\Node\FatalException] "CDPPage.querySelector is not a function"

Begin of the dump of $page:
![image](https://github.com/zoonru/puphpeteer/assets/23262428/eef31fc8-1534-4b08-9087-1762b712b5cf)

NB: My code was previously writed for nesk/puphpepeteer and I try to switch.

**Comment by sylvainlepetit** [comment]
The problem come from a bad install version (1.6.0).

**Comment by meyer59** [comment]
Hey
I am facing the same issue, my install seems fine though, how did you manage to solved this precisely?
Thanks
